/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author AMGambo
 */
public class PopUpAgregarConsultaSQL extends javax.swing.JFrame {

    /**
     * Creates new form PopUpEliminar
     */
    public PopUpAgregarConsultaSQL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelarpopAgregarConsultaSQL = new javax.swing.JButton();
        btnGuardarpopAgregarConsultaSQL = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNombrepopAgregarConsultaSQL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionpopAgregarConsultaSQL = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtQuerypopAgregarConsultaSQL = new javax.swing.JTextArea();
        btnProbarConsultapopAgregarConsultaSQL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 78, 151));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTA SQL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 615, -1));

        btnCancelarpopAgregarConsultaSQL.setBackground(new java.awt.Color(99, 101, 106));
        btnCancelarpopAgregarConsultaSQL.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnCancelarpopAgregarConsultaSQL.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarpopAgregarConsultaSQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelar.png"))); // NOI18N
        btnCancelarpopAgregarConsultaSQL.setText(" CANCELAR");
        btnCancelarpopAgregarConsultaSQL.setBorder(null);
        btnCancelarpopAgregarConsultaSQL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarpopAgregarConsultaSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarpopAgregarConsultaSQLActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarpopAgregarConsultaSQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 435, 160, 33));

        btnGuardarpopAgregarConsultaSQL.setBackground(new java.awt.Color(0, 78, 151));
        btnGuardarpopAgregarConsultaSQL.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnGuardarpopAgregarConsultaSQL.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarpopAgregarConsultaSQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/guardar.png"))); // NOI18N
        btnGuardarpopAgregarConsultaSQL.setText("GUARDAR");
        btnGuardarpopAgregarConsultaSQL.setBorder(null);
        btnGuardarpopAgregarConsultaSQL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarpopAgregarConsultaSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarpopAgregarConsultaSQLActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarpopAgregarConsultaSQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 435, 160, 33));

        jLabel6.setText("Nombre consulta");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 50, 130, -1));
        jPanel1.add(txtNombrepopAgregarConsultaSQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 70, 153, -1));

        jLabel7.setText("Descripcion consulta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 50, 155, -1));

        txtDescripcionpopAgregarConsultaSQL.setColumns(20);
        txtDescripcionpopAgregarConsultaSQL.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionpopAgregarConsultaSQL);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 70, 370, 40));

        jLabel8.setText("Consulta SQL");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 141, 101, -1));

        txtQuerypopAgregarConsultaSQL.setColumns(20);
        txtQuerypopAgregarConsultaSQL.setRows(5);
        txtQuerypopAgregarConsultaSQL.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtQuerypopAgregarConsultaSQL);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 161, 580, 250));

        btnProbarConsultapopAgregarConsultaSQL.setBackground(new java.awt.Color(21, 165, 75));
        btnProbarConsultapopAgregarConsultaSQL.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 10)); // NOI18N
        btnProbarConsultapopAgregarConsultaSQL.setForeground(new java.awt.Color(255, 255, 255));
        btnProbarConsultapopAgregarConsultaSQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/validar.png"))); // NOI18N
        btnProbarConsultapopAgregarConsultaSQL.setText("PROBAR CONSULTA");
        btnProbarConsultapopAgregarConsultaSQL.setBorder(null);
        btnProbarConsultapopAgregarConsultaSQL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProbarConsultapopAgregarConsultaSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbarConsultapopAgregarConsultaSQLActionPerformed(evt);
            }
        });
        jPanel1.add(btnProbarConsultapopAgregarConsultaSQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 130, 140, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProbarConsultapopAgregarConsultaSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbarConsultapopAgregarConsultaSQLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProbarConsultapopAgregarConsultaSQLActionPerformed

    private void btnGuardarpopAgregarConsultaSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarpopAgregarConsultaSQLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarpopAgregarConsultaSQLActionPerformed

    private void btnCancelarpopAgregarConsultaSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarpopAgregarConsultaSQLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarpopAgregarConsultaSQLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpAgregarConsultaSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpAgregarConsultaSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpAgregarConsultaSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpAgregarConsultaSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUpAgregarConsultaSQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarpopAgregarConsultaSQL;
    public javax.swing.JButton btnGuardarpopAgregarConsultaSQL;
    public javax.swing.JButton btnProbarConsultapopAgregarConsultaSQL;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea txtDescripcionpopAgregarConsultaSQL;
    public javax.swing.JTextField txtNombrepopAgregarConsultaSQL;
    public javax.swing.JTextArea txtQuerypopAgregarConsultaSQL;
    // End of variables declaration//GEN-END:variables
}
